version: '3.8'

services:
  edgeanalytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edgeanalytics
    volumes:
      - .:/app  # Mount the current directory to the container for live updates
    ports:
      - "8051:8089"  # Map port 8089 on the host to port 8089 in the container